# Generated by Django 4.0.2 on 2022-03-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('tech', 'technical'), ('fashion', 'fashion'), ('toy', 'toys'), ('furniture', 'furniture'), ('livestyle', 'livestyle')], max_length=16),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_href',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
