# Generated by Django 4.0.2 on 2022-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_category_alter_auction_image_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_href',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
