# Generated by Django 4.0.2 on 2022-03-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_winner_user_watchlist_alter_auction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
